### ISSUE TITLE
Install php extension which is not available in bref

### ISSUE THREAD

**Issue by hafsalmetvr** [umihico/laravel-lambda-docker-bref#4]
hello @umihico 

I am trying to install php couchbase sdk https://docs.couchbase.com/php-sdk/current/hello-world/start-using-sdk.html. to communicate with couchbase database from my php application

But if try to install using apt-get inside Dockerfile , it says like command not found...This is happening when i use bref/php-80-fpm as base image

How can i slove it?

**Comment by umihico** [comment]
Please show me your command and output exactly?
Or Dockerfile?

**Comment by hafsalmetvr** [comment]
Hi @umihico 

Thank  you for your reply

below is my Dockerfile

```
FROM bref/php-80-fpm

RUN apt-get update

RUN apt-get install -y wget lsb-release gnupg2

RUN echo "deb http://packages.couchbase.com/ubuntu bionic bionic/main" | tee /etc/apt/sources.list.d/couchbase.list

RUN wget -O - http://packages.couchbase.com/ubuntu/couchbase.key | apt-key  add -

RUN apt-get update

RUN apt-get install -y libcouchbase3 libcouchbase-dev libcouchbase3-tools libcouchbase-dbg libcouchbase3-libev libcouchbase3-libevent

RUN apt-get update

RUN pecl install https://packages.couchbase.com/clients/php/couchbase-3.2.2.tgz

COPY . /var/task

CMD ["public/index.php"]
```

**Comment by umihico** [comment]
Linux has many kind of distribution. If you run `docker run --rm -it --entrypoint '' bref/php-80-fpm bash`, you can get into shell and dig around.

To know what kind of distribution, you shoud run `cat /etc/os-release` in the shell or `RUN` in Dockerfile. You will see output below and you would know the image is amazon linux whose base is CentOS.

```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
VARIANT_ID="202112211922-2.0.695.0"
```

So please try `yum update` or `yum install` instead of `apt`
